-module(euler_two).
-export([main/0]).

%% Project Euler problem 2

%% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
%% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib(N) ->
    fib(N, 0, 1, [0]).

fib(0, Current, Next, Fibs) ->
    lists:reverse(Fibs); % Reverse the list as the order is important

fib(N, Current, Next, Fibs) ->
    fib(N - 1, Next, Current + Next, [Next | Fibs]).

max_fib(Max) ->
    max_fib(max, []).
max_fib(Max, []) ->
    Z = 1,
    max_fib(Max, [fib(Z)], Z).
max_fib(Max, [_|T], Curr)
  when T >= Max ->
    Fibs ++ [T];
  when T < Max ->
    max_fib(Max, Fibs ++ [T], T).

main() ->
    fib(10).
