#!/usr/bin/env python
"""
Project Euler problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

def max_fibonacci(max_val):
    # generator to recurse over Fibonacci sequence
    previous = 0
    current = 1
    while current < max_val:
        _current = current
        current = current + previous
        previous = _current
        yield current

print sum([x for x in max_fibonacci(4000000) if x % 2 == 0])
